# Generated by Django 5.1.3 on 2024-12-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0002_salaryprocessing_bank_details_salaryprocessing_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryprocessing',
            name='bank_details',
        ),
    ]
