# Generated by Django 5.1.3 on 2024-12-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0003_remove_salaryprocessing_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxmanagement',
            name='income_tax',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='taxmanagement',
            name='other_taxes',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
