# Generated by Django 5.1.3 on 2024-12-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('nic', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('emergency_person', models.CharField(max_length=255)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('job_number', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skills', models.CharField(max_length=255)),
                ('immediate_supervisor', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('resume', models.CharField(max_length=255)),
                ('nic_front', models.CharField(max_length=255)),
                ('nic_back', models.CharField(max_length=255)),
                ('passport', models.CharField(max_length=255)),
                ('service_letter', models.CharField(max_length=255)),
                ('certificate_of_grama_niladhari', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('account_number', models.BigIntegerField()),
                ('account_holder', models.CharField(max_length=255)),
                ('bank_code', models.IntegerField()),
                ('branch_code', models.IntegerField()),
                ('swift_code', models.CharField(max_length=50)),
            ],
        ),
    ]
