# Generated by Django 5.1.3 on 2024-12-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_management', '0002_education_workhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='certificate_of_grama_niladhari',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nic_back',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nic_front',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='service_letter',
        ),
        migrations.AddField(
            model_name='workhistory',
            name='position',
            field=models.CharField(default='Manager', max_length=100),
        ),
    ]
