# Generated by Django 5.1.3 on 2024-12-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_management', '0004_remove_workhistory_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
