# Generated by Django 5.1.3 on 2024-12-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emp_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('feedback', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interviews', to='emp_management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FinalSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_clearance', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_settlements', to='emp_management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RecordKeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_records', models.TextField()),
                ('exit_letter', models.TextField()),
                ('service_letter', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_keeping', to='emp_management.employee')),
            ],
        ),
    ]
