# Generated by Django 5.1.3 on 2024-12-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_management', '0003_remove_employee_certificate_of_grama_niladhari_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhistory',
            name='salary',
        ),
    ]
